### ISSUE TITLE
Blank Windows After Entering Civitai Link Key

### ISSUE THREAD

**Issue by Doctor0S** [civitai/civitai-link-desktop#26]
Do the install and get the program running, go to the site and get the link key and enter it into the code field.  Then clicking next leads me to this screen 

![image](https://github.com/civitai/civitai-link-desktop/assets/131542511/5118e13e-739b-457e-88f1-c497e8c69991)

**Comment by cmoody** [comment]
Hey @Doctor0S I think I have fixed the issue you are running into in the latest patch. (1.14.3) Additionally if you are still getting this can you right-click on the icon in the tray and open devtools. If you send a screenshot that will help me identify a little more. Thanks for the help on this.

**Comment by Doctor0S** [comment]
> Hey @Doctor0S I think I have fixed the issue you are running into in the latest patch. (1.14.3) Additionally if you are still getting this can you right-click on the icon in the tray and open devtools. If you send a screenshot that will help me identify a little more. Thanks for the help on this.

Thank you so much this did allow me to proceed forward, now I am having the issue of a connection loop.  I am assuming its tied to the larger library that I have, but I am unable to open the dev tools the program just freezes

**Comment by cmoody** [comment]
Hey @Doctor0S sorry for the late reply. I think the connection loop is tied to the app trying to send a list of all your files to the site and it being over the 1MB limit default in socketio. Ive made adjustments to the server to see if 5MB will fix things. Im also working on a fix to the app that will decrease the amount of data sent. That should be going out sometime tomorrow hopefully. In the meantime try again and let me know if the increased message limit worked or not.

**Comment by Doctor0S** [comment]
It seems like it's working more consistently on the site but it still isn't updating the files I'll try a reinstall when the new version comes out.

**Comment by Doctor0S** [comment]
> Hey @Doctor0S sorry for the late reply. I think the connection loop is tied to the app trying to send a list of all your files to the site and it being over the 1MB limit default in socketio. Ive made adjustments to the server to see if 5MB will fix things. Im also working on a fix to the app that will decrease the amount of data sent. That should be going out sometime tomorrow hopefully. In the meantime try again and let me know if the increased message limit worked or not.

The increased limit seems to have done the trick, everything is functioning correctly now.

**Comment by cmoody** [comment]
Awesome to hear! Ive got a few more updates coming soon that should help with a handful of the other issues. After that we will be tackling some of the memory issues and more performance improvements.
