### ISSUE TITLE
Link 1.15.2 randomly closing or not responding

### ISSUE THREAD

**Issue by Brennok** [civitai/civitai-link-desktop#40]
I updated to 1.15.2 and everything appeared to be fine, but I found it randomly closed when I came back to my PC.  During the initial start it did find a bunch of new models so subfolders does seem to be working. 

I did restart it, but after a little bit it now shows as Not Responding. I had to quit it via the task manager since right click on the icon also did nothing. Civitai.com also showed no longer connected. Task manager showed activity along with my fans spinning up, but I let it sit for a good 20 minutes with no change.

I restarted it a third time so waiting to see what happens. 

[main.log](https://github.com/civitai/civitai-link-desktop/files/15099140/main.log)

**Comment by cmoody** [comment]
Looks like some image downloads give a weird error thats not being caught correctly.
```
  message: '<No error message>',
  name: 'AggregateError',
```
Wondering if that causes the app to hang. Ive got a new library for downloading stuff I wanted to try to see if it resolves a few issues so Ill give it a whirl here and see what happens.

**Comment by cmoody** [comment]
@Brennok I tried a new way to download stuff and it didnt go well. I think there was something else that I fixed for this. 🤞 1.18.0 resolves the issue but will keep this open so we can watch out to see if it happens again.
