### ISSUE TITLE
[Feature Request] Support for Dora and Pony Model Type

### ISSUE THREAD

**Issue by thiagojramos** [civitai/civitai-link-desktop#49]
I would like to request support for downloading Dora models via the link app. Since the site has a defined category for Dora, implementing this feature should be straightforward.

Additionally, it would be great if the app could support defining the "Pony" model type in the .json configuration.

Thanks! ☺️

**Comment by cmoody** [comment]
@thiagojramos Let me check with the team but we should definitely do this. As for Pony models in the json file. That should be in now. Let me know if you arent seeing it correctly and Ill dig in.

**Comment by thiagojramos** [comment]
Thanks, @cmoody! I appreciate the quick response.

Regarding the Pony models, they still appear as "unknown" in the .json files on my end. Additionally, I noticed the new loading progress bar for models, which looks great! It's interesting how it progresses and then regresses at times, instead of just moving forward.

One more thing, the app still doesn't download the ".preview" files for animated images that are the first ones on the site.

Thanks again for the ongoing improvements!

**Comment by cmoody** [comment]
Ok got it figured out. In some places we have it as PONY and others Pony. I wasnt checking case insensitive. Getting a patch out for this today.
