### ISSUE TITLE
Civiai Link incorrect Checkpoint folder (v 1.18.0)

### ISSUE THREAD

**Issue by jimojo** [civitai/civitai-link-desktop#51]
The correct path for checkpoints in automatic1111 is models/Stable-diffusion .

Civitai Link sets and only registers checkpoints in models/Checkpoints instead of the correct path.

Checkpoints placed in the new Checkpoints folder can't be opened in the webui.

Checkpoints placed in models/Stable-diffusion are ignored and do not appear in Civitai Link.

The models/Checkpoints path where Civitai Link looks for checkpoints cannot be altered in settings.

**Comment by cmoody** [comment]
Hey @jimojo this should be fix in 1.18.0. I just tested on my end from scratch and it looks correct. If you choose Automatic 1111 at the start and your base model folder then it should all be correct by default.

Also not noticing any issues with changing a folder in the settings.

Couple of things to help debug. What OS are you using? Also if you could try changing folders again and then post your logs from after that change.
```
on Linux: ~/.config/{app name}/logs/main.log
on macOS: ~/Library/Logs/{app name}/main.log
on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\main.log
```

Hopefully that can give us some insight to get this fixed for you.

**Comment by jimojo** [comment]
I'm sorry, I was mistaken. I can change the paths the app looks in. The folder buttons in settings open the path to the default folder but I didn't realize I could set a different path. Again, sorry for not paying better attention.

**Comment by cmoody** [comment]
No worries! Glad its working. Feel free to open another issue if you run into more problems.
